name: build lint and test

on: 
    - push
    - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup go
      uses: actions/setup-go@v2

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: "8.0"
        mongodb-port: "27017"

    - name: test
      run: |
        go test -v -cover ./...